# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building code..."
    - echo "Complete."

unit-test-job:
  stage: test
  script:
    - echo "Performing Tests.."
    - echo "Complete."

deploy-job:
  stage: deploy
  script:
    - echo "Deployed"