#Installs Logstash

- name: Install Logstash
  hosts: elk_nodes
  remote_user: azureuser
  become: yes
  roles:
    - role: geerlingguy.logstash
  vars:
    logstash_version: '7.x'
    logstash_package: logstash
    logstash_listen_port_beats: 5044
    logstash_elasticsearch_hosts:
      - https://localhost:9200
    logstash_dir: /usr/share/logstash
    logstash_ssl_dir: /etc/pki/logstash
    logstash_ssl_certificate_file: "~/keys/certs/logstash/logstash.crt"
    logstash_ssl_key_file: "~/keys/certs/logstash/logstash.key"
    logstash_local_syslog_path: /var/log/syslog
    logstash_monitor_local_syslog: true
    logstash_enabled_on_boot: true
    logstash_install_plugins:
      - logstash-input-beats
      - logstash-filter-multiline
